export const AGENT_WALLET_TABLE = 'AgentWallet'
export const AGENT_TABLE = 'Agent'
export const CHANNEL_TABLE = 'Channel'
export const MESSAGE_TABLE = 'Message'
export const SETTINGS_TABLE = 'Settings'
