export const COST_OF_SENDING_MESSAGE = 1

export const MINIMUM_CREDIT_LIMIT = 1

export const DEFAULT_CREDIT_LIMIT = MINIMUM_CREDIT_LIMIT

export const DEFAULT_COMMUNITY_SHARE_POINTS = 100

export const DEFAULT_DEMURRAGE_RATE = 0.02

/** in milliseconds */
export const LENGTH_OF_DAY = 1000 * 60 * 60 * 24

/** in milliseconds */
export const DEFAULT_DEMURRAGE_PERIOD = LENGTH_OF_DAY

export const MAX_PRECISION_IN_AGENT_AMOUNTS = 3

export const STATISTICS_FORGET_FACTOR = 0.85

export const STATISTICS_FORGET_FACTOR_PERIOD = LENGTH_OF_DAY
